# Generated by Django 5.1.7 on 2025-04-07 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_metering', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIMetering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_count', models.IntegerField(default=0)),
                ('post_count', models.IntegerField(default=0)),
                ('put_count', models.IntegerField(default=0)),
                ('delete_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('daily_count', models.IntegerField(default=0)),
                ('daily_reset', models.DateField(auto_now=True)),
                ('last_request', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
