# Generated by Django 5.1.7 on 2025-04-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_metering', '0003_subscriptionplan_remove_apimetering_daily_reset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_metered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_subscription_item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
