# Generated by Django 5.1.7 on 2025-04-03 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_apimetering_daily_limit_apimetering_total_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimetering',
            name='last_reset',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
